# Generated by Django 2.0.6 on 2018-08-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='BabyName',
            field=models.CharField(default='Jack', max_length=20),
            preserve_default=False,
        ),
    ]
