# Generated by Django 2.0.6 on 2018-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(db_column='UserId')),
                ('ImageName', models.CharField(db_column='ImageName', max_length=60)),
                ('Image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
