# Generated by Django 2.0.6 on 2018-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_paint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField(db_column='UserId')),
                ('ImageName', models.CharField(db_column='PaintName', max_length=60)),
                ('Image', models.ImageField(upload_to='paint')),
            ],
        ),
    ]
