# Generated by Django 2.0.6 on 2018-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_covered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covered',
            name='Image',
            field=models.ImageField(upload_to='covered'),
        ),
        migrations.AlterField(
            model_name='covered',
            name='ImageName',
            field=models.CharField(db_column='CoveredName', max_length=60),
        ),
    ]
